apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-boutique-frontend
spec:
  selector:
    matchLabels:
      app: r-boutique-frontend
  template:
    metadata:
      labels:
        app: r-boutique-frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        ves.io.virtual-sites: shared/ves-io-sgp
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: gcr.io/solutions-team-280017/boutique-frontend:v0.3.6
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "boutique-productcatalogservice:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "boutique-currencyservice:7000"
          - name: CART_SERVICE_ADDR
            value: "boutique-cartservice:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "boutique-recommendationservice:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "boutique-shippingservice:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "boutique-checkoutservice:5050"
          - name: AD_SERVICE_ADDR
            value: "boutique-adservice:9555"
          # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba, f5xc
          # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp 
          - name: ENV_PLATFORM 
            value: "f5xc"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          # - name: CYMBAL_BRANDING
          #   value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
